/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    CMSButtonTable: typeof import('./src/components/CMSButtonTable.vue')['default']
    CMSComponentPalette: typeof import('./src/components/CMSComponentPalette.vue')['default']
    CMSContentArea: typeof import('./src/components/CMSContentArea.vue')['default']
    CMSContentBlock: typeof import('./src/components/CMSContentBlock.vue')['default']
    CMSContentBlockEditDialog: typeof import('./src/components/CMSContentBlockEditDialog.vue')['default']
    CMSMetadataPanel: typeof import('./src/components/CMSMetadataPanel.vue')['default']
    CMSProjectExploreDialog: typeof import('./src/components/CMSProjectExploreDialog.vue')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Form: typeof import('@primevue/forms/form')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Textarea: typeof import('primevue/textarea')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
}
